services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:15672"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sistema_certificados
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql/bd.sql:/docker-entrypoint-initdb.d/bd.sql 
    ports:
      - "3306:3306"
    restart: always

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=userpassword
      - DB_DATABASE=sistema_certificados
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
    ports:
      - "8080:8080"
    volumes:
      - ./arquivos:/arquivos
    restart: always

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
    command: ["node", "index.js"]
    volumes:
      - ./arquivos:/arquivos
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    environment:
      - REDISINSIGHT_AUTH_USERNAME=admin
      - REDISINSIGHT_AUTH_PASSWORD=admin123s

volumes:
  mysqldata:
  rabbitmq_data:
