services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:15672"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sistema_certificados
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql/bd.sql:/docker-entrypoint-initdb.d/bd.sql 
    ports:
      - "3306:3306"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mysql
    environment:
      - DB_HOST=mysql-certificados
      - DB_USER=user
      - DB_PASSWORD=userpassword
      - DB_DATABASE=sistema_certificados
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "3000:3000"

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    # depends_on:
    #   rabbitmq:
    #     condition: service_healthy
    #   mysql:
    #     condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
    command: ["node", "index.js"]
    volumes:
      - ./arquivos:/arquivos

volumes:
  mysqldata:
  rabbitmq_data:
